# Generated by Django 4.0.4 on 2022-04-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
