# Generated by Django 4.0.4 on 2022-04-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_app', '0002_remove_trip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tripdestination',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdestination',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
