# Generated by Django 4.0.4 on 2022-04-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_app', '0003_alter_trip_description_alter_tripdestination_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdestination',
            name='order',
        ),
    ]
